
[window]
padding = { x = 10, y = 10 }
opacity = 0.8

[font]
normal= { family = "JetBrains Mono NerdFont", style = "regular" }

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = false

[general]
import = [ "~/.config/alacritty/theme.toml" ]
